package_rename_config:
  android:
    app_name: Package Rename Demo
    package_name: rocks.outdatedguy.packagerenamedemo

  ios:
    app_name: Package Rename Demo
    bundle_name: renamedemo
    package_name: rocks.outdatedguy.packagerenamedemo

  web:
    app_name: Package Rename Demo
    description: Package to change project configurations.

  linux:
    app_name: Package Rename Demo
    package_name: rocks.outdatedguy.packagerenamedemo

  windows:
    app_name: Package Rename Demo
    organization: OutdatedGuy
    copyright_notice: Copyright ©️ 2022 OutdatedGuy. All rights reserved.
