name: package_rename
description: A sample command-line application.
version: 1.0.0
homepage: https://outdatedguy.rocks

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  html: ^0.15.0
  logger: ^1.1.0
  universal_io: ^2.0.4
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
